/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Climatizacion.Climatizacion;
import Climatizacion.VelocidadAbanico;

/**
 *
 * @author Farid
 */
public class FrmClimatizacion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmClimatizacion.class.getName());
        private Climatizacion climatizacion = new Climatizacion();

    /**
     * Creates new form FrmClimatizacion
     */
    public FrmClimatizacion() {
        initComponents();
        actualizarInterfaz();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTemperatura = new javax.swing.JLabel();
        lblVelocidad = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        btnSubirTemp = new javax.swing.JButton();
        btnBajarTemp = new javax.swing.JButton();
        btnEncenderAC = new javax.swing.JButton();
        btnEncenderCalef = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnVelocidadAlta = new javax.swing.JButton();
        btnVelocidadBaja = new javax.swing.JButton();
        btnVelocidadMedia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTemperatura.setText("TEMPERATURA");

        lblVelocidad.setText("VELOCIDAD");

        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado.setText("ESTADO");

        btnSubirTemp.setBackground(new java.awt.Color(51, 51, 255));
        btnSubirTemp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSubirTemp.setForeground(new java.awt.Color(0, 0, 0));
        btnSubirTemp.setText("+ Temp");
        btnSubirTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirTempActionPerformed(evt);
            }
        });

        btnBajarTemp.setBackground(new java.awt.Color(255, 51, 51));
        btnBajarTemp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBajarTemp.setForeground(new java.awt.Color(0, 0, 0));
        btnBajarTemp.setText("- Temp");
        btnBajarTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajarTempActionPerformed(evt);
            }
        });

        btnEncenderAC.setBackground(new java.awt.Color(0, 0, 0));
        btnEncenderAC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEncenderAC.setForeground(new java.awt.Color(255, 255, 255));
        btnEncenderAC.setText("A/C");
        btnEncenderAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderACActionPerformed(evt);
            }
        });

        btnEncenderCalef.setBackground(new java.awt.Color(0, 0, 0));
        btnEncenderCalef.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEncenderCalef.setForeground(new java.awt.Color(255, 255, 255));
        btnEncenderCalef.setText("Calefaccion");
        btnEncenderCalef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderCalefActionPerformed(evt);
            }
        });

        btnApagar.setBackground(new java.awt.Color(255, 102, 0));
        btnApagar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnApagar.setForeground(new java.awt.Color(255, 255, 255));
        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnVelocidadAlta.setBackground(new java.awt.Color(0, 0, 0));
        btnVelocidadAlta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVelocidadAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnVelocidadAlta.setText("ALTA");
        btnVelocidadAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVelocidadAltaActionPerformed(evt);
            }
        });

        btnVelocidadBaja.setBackground(new java.awt.Color(0, 0, 0));
        btnVelocidadBaja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVelocidadBaja.setForeground(new java.awt.Color(255, 255, 255));
        btnVelocidadBaja.setText("BAJA");
        btnVelocidadBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVelocidadBajaActionPerformed(evt);
            }
        });

        btnVelocidadMedia.setBackground(new java.awt.Color(0, 0, 0));
        btnVelocidadMedia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVelocidadMedia.setForeground(new java.awt.Color(255, 255, 255));
        btnVelocidadMedia.setText("MEDIA");
        btnVelocidadMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVelocidadMediaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSubirTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBajarTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(btnEncenderCalef)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                        .addComponent(btnVelocidadMedia))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addComponent(btnEncenderAC, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnVelocidadAlta))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnVelocidadBaja)))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSubirTemp)
                            .addComponent(btnEncenderAC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnVelocidadAlta)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBajarTemp)
                        .addComponent(btnEncenderCalef, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVelocidadMedia))
                .addGap(18, 18, 18)
                .addComponent(btnVelocidadBaja)
                .addGap(61, 61, 61)
                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void actualizarInterfaz() {
    lblTemperatura.setText("Temperatura: " + climatizacion.getTemperatura() + "°C");
        lblVelocidad.setText("Velocidad: " + climatizacion.getVelocidad());
        
        if (climatizacion.isAireAcondicionadoEncendido()) {
            lblEstado.setText("Aire Acondicionado Activado");
        } else if (climatizacion.isCalefaccionEncendida()) {
            lblEstado.setText("Calefacción Activada");
        } else {
            lblEstado.setText("Sistema Apagado");
        }
}
    


    private void btnBajarTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajarTempActionPerformed
        climatizacion.bajarTemperatura();
        actualizarInterfaz();
    }//GEN-LAST:event_btnBajarTempActionPerformed

    private void btnEncenderACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderACActionPerformed
        climatizacion.encenderAireAcondicionado();
        actualizarInterfaz();
    }//GEN-LAST:event_btnEncenderACActionPerformed

    private void btnEncenderCalefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderCalefActionPerformed
       climatizacion.encenderCalefaccion();
        actualizarInterfaz();
    }//GEN-LAST:event_btnEncenderCalefActionPerformed

    private void btnVelocidadMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVelocidadMediaActionPerformed
        climatizacion.setVelocidadVentilador(VelocidadAbanico.MEDIA);
        actualizarInterfaz();
    }//GEN-LAST:event_btnVelocidadMediaActionPerformed

    private void btnVelocidadAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVelocidadAltaActionPerformed
        climatizacion.setVelocidadVentilador(VelocidadAbanico.ALTA);
        actualizarInterfaz();
    }//GEN-LAST:event_btnVelocidadAltaActionPerformed

    private void btnSubirTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirTempActionPerformed
        climatizacion.subirTemperatura();
        actualizarInterfaz();
    }//GEN-LAST:event_btnSubirTempActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        climatizacion.apagarAireAcondicionado();
        climatizacion.apagarCalefaccion();
        climatizacion.setVelocidadVentilador(VelocidadAbanico.APAGADO);
        actualizarInterfaz();
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnVelocidadBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVelocidadBajaActionPerformed
        climatizacion.setVelocidadVentilador(VelocidadAbanico.BAJA);
        actualizarInterfaz();
    }//GEN-LAST:event_btnVelocidadBajaActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmClimatizacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnBajarTemp;
    private javax.swing.JButton btnEncenderAC;
    private javax.swing.JButton btnEncenderCalef;
    private javax.swing.JButton btnSubirTemp;
    private javax.swing.JButton btnVelocidadAlta;
    private javax.swing.JButton btnVelocidadBaja;
    private javax.swing.JButton btnVelocidadMedia;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblTemperatura;
    private javax.swing.JLabel lblVelocidad;
    // End of variables declaration//GEN-END:variables

}