/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Escobillas.Escobilla;
import Escobillas.Velocidades;

/**
 *
 * @author Farid
 */
public class FrmEscobillas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEscobillas.class.getName());
        private Escobilla escobilla = new Escobilla();
    /**
     * Creates new form FrmEscobillas
     */
    public FrmEscobillas() {
        initComponents();
        actualizarInterfaz();
        lblEscobillas.setVisible(false);
        lblParabrisas.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEstado = new javax.swing.JLabel();
        lblVelocidad = new javax.swing.JLabel();
        btnEncender = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        btnMedia = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        lblParabrisas = new javax.swing.JLabel();
        lblEscobillas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEstado.setText("jLabel1");

        lblVelocidad.setText("jLabel1");

        btnEncender.setBackground(new java.awt.Color(0, 0, 0));
        btnEncender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEncender.setForeground(new java.awt.Color(255, 255, 255));
        btnEncender.setText("Encender");
        btnEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderActionPerformed(evt);
            }
        });

        btnApagar.setBackground(new java.awt.Color(0, 0, 0));
        btnApagar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnApagar.setForeground(new java.awt.Color(255, 255, 255));
        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnAlta.setBackground(new java.awt.Color(204, 204, 204));
        btnAlta.setForeground(new java.awt.Color(0, 0, 0));
        btnAlta.setText("ALTA");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnMedia.setBackground(new java.awt.Color(204, 204, 204));
        btnMedia.setForeground(new java.awt.Color(0, 0, 0));
        btnMedia.setText("MEDIA");
        btnMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaActionPerformed(evt);
            }
        });

        btnBaja.setBackground(new java.awt.Color(204, 204, 204));
        btnBaja.setForeground(new java.awt.Color(0, 0, 0));
        btnBaja.setText("BAJA");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        lblParabrisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Parabrisas.jpg"))); // NOI18N

        lblEscobillas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Escobillas.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEncender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAlta)
                    .addComponent(lblVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedia)
                    .addComponent(btnBaja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(lblParabrisas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEscobillas, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEscobillas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblParabrisas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblVelocidad, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnEncender, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnAlta)
                                .addGap(18, 18, 18)
                                .addComponent(btnMedia)
                                .addGap(18, 18, 18)
                                .addComponent(btnBaja)))))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void actualizarInterfaz() {
    
        if (escobilla.estaEncendido()) {
            lblEstado.setText("Encendido");
            lblVelocidad.setText("Velocidad: " + escobilla.getVelocidadActual());
            lblEscobillas.setVisible(true);
            lblParabrisas.setVisible(false);
        } else {
            lblEstado.setText("Apagado");
            lblVelocidad.setText("Velocidad: -");
            lblParabrisas.setVisible(true);
            lblEscobillas.setVisible(false);
        }
    }
    private void btnEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderActionPerformed
        escobilla.encender(Velocidades.BAJA);
        actualizarInterfaz();
    }//GEN-LAST:event_btnEncenderActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        escobilla.apagar();
        actualizarInterfaz();
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        escobilla.cambiarVelocidad(Velocidades.ALTA);
        actualizarInterfaz();
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaActionPerformed
        escobilla.cambiarVelocidad(Velocidades.MEDIA);
        actualizarInterfaz();
    }//GEN-LAST:event_btnMediaActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        escobilla.cambiarVelocidad(Velocidades.BAJA);
        actualizarInterfaz();
    }//GEN-LAST:event_btnBajaActionPerformed


   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmEscobillas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnEncender;
    private javax.swing.JButton btnMedia;
    private javax.swing.JLabel lblEscobillas;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblParabrisas;
    private javax.swing.JLabel lblVelocidad;
    // End of variables declaration//GEN-END:variables
}
