/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Carro.AlarmaYBloqueo;
import Puertas.tipoPuerta;
import Puertas.ControladorPuertas;


/**
 *
 * @author Farid
 */
public class FrmPuertas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPuertas.class.getName());
        private ControladorPuertas controlador = new ControladorPuertas();
        private AlarmaYBloqueo sistemaSeguridad = new AlarmaYBloqueo();

    /**
     * Creates new form FrmPuertas
     */
    public FrmPuertas() {
        initComponents();
        lblPuertaIzq.setVisible(false);
        lblPuertaDer.setVisible(false);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDelIzq = new javax.swing.JButton();
        btnTrasDer = new javax.swing.JButton();
        btnDelDer = new javax.swing.JButton();
        btnTrasIzq = new javax.swing.JButton();
        lblPuertaIzq = new javax.swing.JLabel();
        lblPuertaDer = new javax.swing.JLabel();
        btnSeguroGeneral = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDelIzq.setBackground(new java.awt.Color(255, 255, 255));
        btnDelIzq.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelIzq.setForeground(new java.awt.Color(0, 0, 0));
        btnDelIzq.setText("Abrir Del Izq");
        btnDelIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelIzqActionPerformed(evt);
            }
        });

        btnTrasDer.setBackground(new java.awt.Color(255, 255, 255));
        btnTrasDer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTrasDer.setForeground(new java.awt.Color(0, 0, 0));
        btnTrasDer.setText("Abrir Tras Der");
        btnTrasDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrasDerActionPerformed(evt);
            }
        });

        btnDelDer.setBackground(new java.awt.Color(255, 255, 255));
        btnDelDer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelDer.setForeground(new java.awt.Color(0, 0, 0));
        btnDelDer.setText("Abrir Del Der");
        btnDelDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelDerActionPerformed(evt);
            }
        });

        btnTrasIzq.setBackground(new java.awt.Color(255, 255, 255));
        btnTrasIzq.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTrasIzq.setForeground(new java.awt.Color(0, 0, 0));
        btnTrasIzq.setText("Abrir Tras Izq");
        btnTrasIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrasIzqActionPerformed(evt);
            }
        });

        lblPuertaIzq.setBackground(new java.awt.Color(255, 255, 0));
        lblPuertaIzq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuertaIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagen nueva.png"))); // NOI18N

        lblPuertaDer.setBackground(new java.awt.Color(255, 255, 255));
        lblPuertaDer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuertaDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/car-door der.png"))); // NOI18N

        btnSeguroGeneral.setBackground(new java.awt.Color(153, 0, 0));
        btnSeguroGeneral.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSeguroGeneral.setForeground(new java.awt.Color(255, 255, 255));
        btnSeguroGeneral.setText("Activar Seguro");
        btnSeguroGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguroGeneralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrasIzq)
                    .addComponent(lblPuertaIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTrasDer, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelDer, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPuertaDer))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSeguroGeneral)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelDer)
                    .addComponent(btnDelIzq))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPuertaDer)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblPuertaIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrasDer)
                    .addComponent(btnTrasIzq))
                .addGap(33, 33, 33)
                .addComponent(btnSeguroGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelIzqActionPerformed
        tipoPuerta tipo = tipoPuerta.DELANTERA_IZQUIERDA;
        if (sistemaSeguridad.isPuertaBloqueada()) {
            controlador.cerrarPuerta(tipo);
            return;
        }
        
    if (controlador.estaAbierta(tipo)) {
        controlador.cerrarPuerta(tipo);
        btnDelIzq.setText("Abrir Del Izq");
        lblPuertaIzq.setVisible(false);
    } else {
        controlador.abrirPuerta(tipo);
        btnDelIzq.setText("Cerrar Del Izq");
        lblPuertaIzq.setVisible(true);
    }
    }//GEN-LAST:event_btnDelIzqActionPerformed

    private void btnTrasDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrasDerActionPerformed
        tipoPuerta tipo = tipoPuerta.TRASERA_DERECHA;
        if (sistemaSeguridad.isPuertaBloqueada()) {
            controlador.cerrarPuerta(tipo);
            return;
        }
        
    if (controlador.estaAbierta(tipo)) {
            controlador.cerrarPuerta(tipo);
            btnTrasDer.setText("Abrir Tras Der");
        } else {
            controlador.abrirPuerta(tipo);
            btnTrasDer.setText("Cerrar Tras Der");
        }
    }//GEN-LAST:event_btnTrasDerActionPerformed

    private void btnDelDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelDerActionPerformed
        tipoPuerta tipo = tipoPuerta.DELANTERA_DERECHA;
        if (sistemaSeguridad.isPuertaBloqueada()) {
            controlador.cerrarPuerta(tipo);
            return;
        }
        
        if (controlador.estaAbierta(tipo)) {
            controlador.cerrarPuerta(tipo);
            btnDelDer.setText("Abrir Del Der");
            lblPuertaDer.setVisible(false);
        } else {
            controlador.abrirPuerta(tipo);
            btnDelDer.setText("Cerrar Del Der");
            lblPuertaDer.setVisible(true);
        }
    }//GEN-LAST:event_btnDelDerActionPerformed

    private void btnTrasIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrasIzqActionPerformed
        tipoPuerta tipo = tipoPuerta.TRASERA_IZQUIERDA;
        if (sistemaSeguridad.isPuertaBloqueada()) {
            controlador.cerrarPuerta(tipo);
            return;
        }

        if (controlador.estaAbierta(tipo)) {
            controlador.cerrarPuerta(tipo);
            btnTrasIzq.setText("Abrir Tras Izq");
        } else {
            controlador.abrirPuerta(tipo);
            btnTrasIzq.setText("Cerrar Tras Izq");
        }
    }//GEN-LAST:event_btnTrasIzqActionPerformed

    private void btnSeguroGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguroGeneralActionPerformed
        
        if (sistemaSeguridad.isPuertaBloqueada()) {
        sistemaSeguridad.desbloquearPuerta();
        btnSeguroGeneral.setText("Activar Seguro");
    } else {
        sistemaSeguridad.bloquearPuerta();
        btnSeguroGeneral.setText("Desactivar Seguro");
        lblPuertaIzq.setVisible(false);
        lblPuertaDer.setVisible(false);

        for (tipoPuerta tipo : tipoPuerta.values()) {
            controlador.cerrarPuerta(tipo);
        }

        // Actualizar los textos de los botones
        btnDelIzq.setText("Abrir Del Izq");
        btnDelDer.setText("Abrir Del Der");
        btnTrasIzq.setText("Abrir Tras Izq");
        btnTrasDer.setText("Abrir Tras Der");
    }
    }//GEN-LAST:event_btnSeguroGeneralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPuertas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelDer;
    private javax.swing.JButton btnDelIzq;
    private javax.swing.JButton btnSeguroGeneral;
    private javax.swing.JButton btnTrasDer;
    private javax.swing.JButton btnTrasIzq;
    private javax.swing.JLabel lblPuertaDer;
    private javax.swing.JLabel lblPuertaIzq;
    // End of variables declaration//GEN-END:variables
}
