/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Kilometraje.ControlKilometraje;
import Luces.SistemaIluminacion;

/**
 *
 * @author Jorge
 */

public class KilometrajeGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KilometrajeGUI.class.getName());

    /**
     * Creates new form KilometrajeGUI
     */
    private ControlKilometraje controlKilometraje = new ControlKilometraje();
    private SistemaIluminacion sistemaIluminacion = new SistemaIluminacion();

    public KilometrajeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEstadoEncendido = new javax.swing.JLabel();
        spnVelocidad = new javax.swing.JSpinner();
        lblVelocidad = new javax.swing.JLabel();
        lblKilometros = new javax.swing.JLabel();
        lblRPM = new javax.swing.JLabel();
        btnActualizarKilometraje = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        chkIntermitentes = new javax.swing.JCheckBox();
        chkLucesPuertas = new javax.swing.JCheckBox();
        chkEmergencia = new javax.swing.JCheckBox();
        chkLucesAltas = new javax.swing.JCheckBox();
        chkLucesBajas = new javax.swing.JCheckBox();
        btnEncender = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEstadoEncendido.setText("Estado: Apagado");

        lblVelocidad.setText("Velocidad actual");

        lblKilometros.setText("Kilómetros recorridos");

        lblRPM.setText("RPM");

        btnActualizarKilometraje.setText("Actualizar");
        btnActualizarKilometraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarKilometrajeActionPerformed(evt);
            }
        });

        jPanel1.setToolTipText("");

        chkIntermitentes.setText("Luces Intermitentes");
        chkIntermitentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIntermitentesActionPerformed(evt);
            }
        });

        chkLucesPuertas.setText("Luces Puertas");
        chkLucesPuertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLucesPuertasActionPerformed(evt);
            }
        });

        chkEmergencia.setText("Luces Emergencia");
        chkEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEmergenciaActionPerformed(evt);
            }
        });

        chkLucesAltas.setText("Luces Altas");
        chkLucesAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLucesAltasActionPerformed(evt);
            }
        });

        chkLucesBajas.setText("Luces Bajas");
        chkLucesBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLucesBajasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(chkLucesPuertas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkIntermitentes)
                    .addComponent(chkLucesAltas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkEmergencia)
                    .addComponent(chkLucesBajas))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkLucesAltas)
                    .addComponent(chkLucesBajas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkEmergencia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkIntermitentes, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkLucesPuertas)
                .addGap(18, 18, 18))
        );

        btnEncender.setText("Estado: Apagado");
        btnEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEstadoEncendido, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVelocidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblKilometros, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(lblRPM, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnActualizarKilometraje)
                                .addGap(56, 56, 56)
                                .addComponent(spnVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(111, 111, 111))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEncender)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKilometros, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRPM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActualizarKilometraje)
                            .addComponent(spnVelocidad)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(lblEstadoEncendido, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEncender)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarKilometrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarKilometrajeActionPerformed
        int velocidad = (int) spnVelocidad.getValue();
        controlKilometraje.setVelocidad(velocidad);
        controlKilometraje.avanzarTiempo(0.1); // simula 6 minutos

        lblVelocidad.setText("Velocidad: " + controlKilometraje.getVelocidadActual() + " km/h");
        lblRPM.setText("RPM: " + controlKilometraje.getRPM());
        lblKilometros.setText("Distancia: " + controlKilometraje.getKilometrosRecorridos() + " km");
    }//GEN-LAST:event_btnActualizarKilometrajeActionPerformed

    private void chkIntermitentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIntermitentesActionPerformed
        if (chkIntermitentes.isSelected()) {
            sistemaIluminacion.activarIntermitentes();
        } else {
            sistemaIluminacion.desactivarIntermitentes();
        }
    }//GEN-LAST:event_chkIntermitentesActionPerformed

    private void chkLucesPuertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLucesPuertasActionPerformed
        if (chkLucesPuertas.isSelected()) {
            sistemaIluminacion.activarLucesPuertas();
        }
    }//GEN-LAST:event_chkLucesPuertasActionPerformed

    private void chkEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEmergenciaActionPerformed
        if (chkEmergencia.isSelected()) {
            sistemaIluminacion.activarEmergencia();
        }
    }//GEN-LAST:event_chkEmergenciaActionPerformed

    private void btnEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderActionPerformed
      if (btnEncender.isSelected()) {
        btnEncender.setText("Apagar vehículo");
        lblEstadoEncendido.setText("Estado: Encendido");
    } else {
        btnEncender.setText("Encender vehículo");
        lblEstadoEncendido.setText("Estado: Apagado");
    }
    }//GEN-LAST:event_btnEncenderActionPerformed

    private void chkLucesAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLucesAltasActionPerformed
       if (chkLucesAltas.isSelected()) {
        chkLucesBajas.setSelected(false);
        sistemaIluminacion.encenderLucesAltas();
    } else {
        sistemaIluminacion.apagarLucesDelanteras();
    }
    }//GEN-LAST:event_chkLucesAltasActionPerformed

    private void chkLucesBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLucesBajasActionPerformed
   if (chkLucesBajas.isSelected()) {
        chkLucesAltas.setSelected(false);
        sistemaIluminacion.encenderLucesBajas();
    } else {
        sistemaIluminacion.apagarLucesDelanteras();
    }
    }//GEN-LAST:event_chkLucesBajasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new KilometrajeGUI().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnActualizarKilometraje;
    private javax.swing.JToggleButton btnEncender;
    private javax.swing.JCheckBox chkEmergencia;
    private javax.swing.JCheckBox chkIntermitentes;
    private javax.swing.JCheckBox chkLucesAltas;
    private javax.swing.JCheckBox chkLucesBajas;
    private javax.swing.JCheckBox chkLucesPuertas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEstadoEncendido;
    private javax.swing.JLabel lblKilometros;
    private javax.swing.JLabel lblRPM;
    private javax.swing.JLabel lblVelocidad;
    private javax.swing.JSpinner spnVelocidad;
    // End of variables declaration//GEN-END:variables
}
