/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Cinturones.TipoCinturon;
import Cinturones.ControladorCinturones;
import Kilometraje.ControlKilometraje;
import Luces.SistemaIluminacion;
import Carro.*;
import javax.swing.Timer;

/**
 *
 * @author Jorge
 */
public class KilometrajeGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KilometrajeGUI.class.getName());

    /**
     * Creates new form KilometrajeGUI
     */
    private Timer timerCargaBateria;
    private Timer timerKilometraje;
    private Timer timerBateria;
    private SistemaBateria bateria = new SistemaBateria();
    private ControlKilometraje controlKilometraje = new ControlKilometraje();
    private SistemaIluminacion sistemaIluminacion = new SistemaIluminacion();
    private ControladorCinturones controlador = new ControladorCinturones();

    public KilometrajeGUI() {
        initComponents();
        spnVelocidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 300, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        spnVelocidad = new javax.swing.JSpinner();
        lblVelocidad = new javax.swing.JLabel();
        lblKilometros = new javax.swing.JLabel();
        lblRPM = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        chkIntermitentes = new javax.swing.JCheckBox();
        chkEmergencia = new javax.swing.JCheckBox();
        chkLucesAltas = new javax.swing.JCheckBox();
        chkLucesBajas = new javax.swing.JCheckBox();
        btnConductor = new javax.swing.JButton();
        btnPasajeroDelantero = new javax.swing.JButton();
        btnTraseroDerecho = new javax.swing.JButton();
        btnTraseroIzquierdo = new javax.swing.JButton();
        lblConductor = new javax.swing.JLabel();
        lblPasajeroDelantero = new javax.swing.JLabel();
        lblAtrasDerecho = new javax.swing.JLabel();
        lblAtrasIzquierdo = new javax.swing.JLabel();
        progressBarNivelBateria = new javax.swing.JProgressBar();
        lblEstadoBateria = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();
        btnParar = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        spnVelocidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnVelocidadStateChanged(evt);
            }
        });

        lblVelocidad.setText("Velocidad actual");

        lblKilometros.setText("Kilómetros recorridos");

        lblRPM.setText("RPM");

        jPanel1.setToolTipText("");

        chkIntermitentes.setText("Luces Intermitentes");
        chkIntermitentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIntermitentesActionPerformed(evt);
            }
        });

        chkEmergencia.setText("Luces Emergencia");
        chkEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEmergenciaActionPerformed(evt);
            }
        });

        chkLucesAltas.setText("Luces Altas");
        chkLucesAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLucesAltasActionPerformed(evt);
            }
        });

        chkLucesBajas.setText("Luces Bajas");
        chkLucesBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLucesBajasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkIntermitentes)
                    .addComponent(chkLucesAltas))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkEmergencia)
                    .addComponent(chkLucesBajas))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkLucesAltas)
                            .addComponent(chkLucesBajas))
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkIntermitentes)
                            .addComponent(chkEmergencia))))
                .addGap(56, 56, 56))
        );

        btnConductor.setText("Abrochar");
        btnConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConductorActionPerformed(evt);
            }
        });

        btnPasajeroDelantero.setText("Abrochar");
        btnPasajeroDelantero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasajeroDelanteroActionPerformed(evt);
            }
        });

        btnTraseroDerecho.setText("Abrochar");
        btnTraseroDerecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraseroDerechoActionPerformed(evt);
            }
        });

        btnTraseroIzquierdo.setText("Abrochar");
        btnTraseroIzquierdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraseroIzquierdoActionPerformed(evt);
            }
        });

        lblConductor.setText("Estado: Desabrochado ");

        lblPasajeroDelantero.setText("Estado: Desabrochado");

        lblAtrasDerecho.setText("Estado: Desabrochado ");

        lblAtrasIzquierdo.setText("Estado: Desabrochado ");

        progressBarNivelBateria.setForeground(new java.awt.Color(255, 153, 0));
        progressBarNivelBateria.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                progressBarNivelBateriaStateChanged(evt);
            }
        });

        lblEstadoBateria.setText("Estado de Bateria");

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        btnParar.setText("Parar");
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(spnVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVelocidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblKilometros, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblRPM, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 62, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTraseroIzquierdo)
                            .addComponent(btnConductor)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblConductor))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAtrasIzquierdo)))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPasajeroDelantero)
                        .addGap(197, 197, 197)
                        .addComponent(btnCargar)
                        .addGap(36, 36, 36)
                        .addComponent(btnParar))
                    .addComponent(lblPasajeroDelantero)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAtrasDerecho)
                            .addComponent(btnTraseroDerecho))
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(progressBarNivelBateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEstadoBateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKilometros, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRPM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConductor)
                    .addComponent(lblPasajeroDelantero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnPasajeroDelantero)
                        .addComponent(btnConductor))
                    .addComponent(btnCargar)
                    .addComponent(btnParar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblAtrasIzquierdo)
                        .addComponent(lblAtrasDerecho))
                    .addComponent(progressBarNivelBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTraseroIzquierdo)
                        .addComponent(btnTraseroDerecho))
                    .addComponent(lblEstadoBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkIntermitentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIntermitentesActionPerformed

        if (chkIntermitentes.isSelected()) {
            iniciarConsumoBateriaContinuo();
            sistemaIluminacion.activarIntermitentes();
        } else {
            sistemaIluminacion.desactivarIntermitentes();
            timerBateria.stop();
        }
    }//GEN-LAST:event_chkIntermitentesActionPerformed

    private void chkEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEmergenciaActionPerformed
        if (chkEmergencia.isSelected()) {
            iniciarConsumoBateriaContinuo();
            sistemaIluminacion.activarEmergencia();
        }
    }//GEN-LAST:event_chkEmergenciaActionPerformed

    private void chkLucesAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLucesAltasActionPerformed
        if (chkLucesAltas.isSelected()) {
            iniciarConsumoBateriaContinuo();
            chkLucesBajas.setSelected(false);
            sistemaIluminacion.encenderLucesAltas();
        } else {
            sistemaIluminacion.apagarLucesDelanteras();
            timerBateria.stop();
        }
    }//GEN-LAST:event_chkLucesAltasActionPerformed

    private void chkLucesBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLucesBajasActionPerformed
        if (chkLucesBajas.isSelected()) {
            iniciarConsumoBateriaContinuo();
            chkLucesAltas.setSelected(false);
            sistemaIluminacion.encenderLucesBajas();
        } else {
            timerBateria.stop();
            sistemaIluminacion.apagarLucesDelanteras();
        }
    }//GEN-LAST:event_chkLucesBajasActionPerformed

    private void btnPasajeroDelanteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasajeroDelanteroActionPerformed
        controlador.cambiarEstadoCinturon(TipoCinturon.PASAJERO_DELANTERO);
        boolean abrochado = controlador.estaAbrochado(TipoCinturon.PASAJERO_DELANTERO);

        lblPasajeroDelantero.setText("Estado: " + (abrochado ? "Abrochado" : "Desabrochado"));
        btnPasajeroDelantero.setText(abrochado ? "Desabrochar" : "Abrochar");

    }//GEN-LAST:event_btnPasajeroDelanteroActionPerformed

    private void btnConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConductorActionPerformed
        controlador.cambiarEstadoCinturon(TipoCinturon.CONDUCTOR);
        boolean abrochado = controlador.estaAbrochado(TipoCinturon.CONDUCTOR);

        lblConductor.setText("Estado: " + (abrochado ? "Abrochado" : "Desabrochado"));
        btnConductor.setText(abrochado ? "Desabrochar" : "Abrochar");
    }//GEN-LAST:event_btnConductorActionPerformed

    private void btnTraseroIzquierdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraseroIzquierdoActionPerformed
        controlador.cambiarEstadoCinturon(TipoCinturon.TRASERO_IZQUIERDO);
        boolean abrochado = controlador.estaAbrochado(TipoCinturon.TRASERO_IZQUIERDO);

        lblAtrasIzquierdo.setText("Estado: " + (abrochado ? "Abrochado" : "Desabrochado"));
        btnTraseroIzquierdo.setText(abrochado ? "Desabrochar" : "Abrochar");
    }//GEN-LAST:event_btnTraseroIzquierdoActionPerformed

    private void btnTraseroDerechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraseroDerechoActionPerformed
        controlador.cambiarEstadoCinturon(TipoCinturon.TRASERO_DERECHO);
        boolean abrochado = controlador.estaAbrochado(TipoCinturon.TRASERO_DERECHO);

        lblAtrasDerecho.setText("Estado: " + (abrochado ? "Abrochado" : "Desabrochado"));
        btnTraseroDerecho.setText(abrochado ? "Desabrochar" : "Abrochar");
    }//GEN-LAST:event_btnTraseroDerechoActionPerformed

    private void spnVelocidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnVelocidadStateChanged
        int nuevaVelocidad = (int) spnVelocidad.getValue();
        controlKilometraje.setVelocidad(nuevaVelocidad);

        if (nuevaVelocidad == 0) {
            timerBateria.stop();
            detenerTimerKilometraje();
        } else {
            iniciarConsumoBateriaContinuo();
            iniciarTimerKilometraje();
        }

        controlKilometraje.setVelocidad(nuevaVelocidad);

        lblVelocidad.setText(nuevaVelocidad + " km/h");

        lblRPM.setText(controlKilometraje.getRPM() + " rpm");

        lblKilometros.setText(String.format("%.2f km", controlKilometraje.getKilometrosRecorridos()));
    }//GEN-LAST:event_spnVelocidadStateChanged

    private void progressBarNivelBateriaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_progressBarNivelBateriaStateChanged

    }//GEN-LAST:event_progressBarNivelBateriaStateChanged

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        if (timerBateria != null && timerBateria.isRunning()) {
            timerBateria.stop();
        }
        iniciarCargaBateriaContinuo();
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
        if (timerCargaBateria != null && timerCargaBateria.isRunning()) {
            timerCargaBateria.stop();
        }
    }//GEN-LAST:event_btnPararActionPerformed

    private void iniciarTimerKilometraje() {
        if (timerKilometraje == null) {
            timerKilometraje = new Timer(1000, e -> {
                controlKilometraje.avanzarUnSegundo();
                lblKilometros.setText(String.format("%.2f km", controlKilometraje.getKilometrosRecorridos()));
            });
            timerKilometraje.start();
        } else if (!timerKilometraje.isRunning()) {
            timerKilometraje.start();
        }
    }

    private void detenerTimerKilometraje() {
        if (timerKilometraje != null && timerKilometraje.isRunning()) {
            timerKilometraje.stop();
        }
    }

    private void actualizarEstadoBateria() {
        int nivel = (int) bateria.getNivelBateria();
        progressBarNivelBateria.setValue(nivel);
        lblEstadoBateria.setText(bateria.estadoBateria());
    }

    private void iniciarCargaBateriaContinuo() {
        if (timerCargaBateria == null || !timerCargaBateria.isRunning()) {
            timerCargaBateria = new javax.swing.Timer(1000, e -> {
                bateria.cargarBateria();
                actualizarEstadoBateria();

                if (bateria.getNivelBateria() >= 100) {
                    bateria.cargarBateria();
                    actualizarEstadoBateria();
                    timerCargaBateria.stop();
                    javax.swing.JOptionPane.showMessageDialog(this, "Bateria completamente cargada");
                }
            });
            timerCargaBateria.start();
        }
    }

    protected void iniciarConsumoBateriaContinuo() {
        if (timerBateria == null || !timerBateria.isRunning()) {
            timerBateria = new javax.swing.Timer(1000, e -> {
                bateria.consumirBateria();
                actualizarEstadoBateria();

                if (bateria.getNivelBateria() <= 0) {
                    timerBateria.stop();
                    javax.swing.JOptionPane.showMessageDialog(this, "La bateria se ha agotado");
                }
            });
            timerBateria.start();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KilometrajeGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnConductor;
    private javax.swing.JButton btnParar;
    private javax.swing.JButton btnPasajeroDelantero;
    private javax.swing.JButton btnTraseroDerecho;
    private javax.swing.JButton btnTraseroIzquierdo;
    private javax.swing.JCheckBox chkEmergencia;
    private javax.swing.JCheckBox chkIntermitentes;
    private javax.swing.JCheckBox chkLucesAltas;
    private javax.swing.JCheckBox chkLucesBajas;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAtrasDerecho;
    private javax.swing.JLabel lblAtrasIzquierdo;
    private javax.swing.JLabel lblConductor;
    private javax.swing.JLabel lblEstadoBateria;
    private javax.swing.JLabel lblKilometros;
    private javax.swing.JLabel lblPasajeroDelantero;
    private javax.swing.JLabel lblRPM;
    private javax.swing.JLabel lblVelocidad;
    private javax.swing.JProgressBar progressBarNivelBateria;
    private javax.swing.JSpinner spnVelocidad;
    // End of variables declaration//GEN-END:variables
}
